export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  const { content, user } = req.body;

  if (!content || !user) {
    return res.status(400).json({ error: 'Missing content or user' });
  }

  console.log(`📨 Message from ${user}: ${content}`);

  // Example: respond with a fake image generation URL
  return res.status(200).json({
    imageUrl: `https://dummyimage.com/600x400/000/fff&text=Hello+${encodeURIComponent(user)}`,
    message: `Image for "${content}" generated by ${user}.`,
  });
}
